MySQL:
  ativar: false
  usuario: root
  senha: ''
  host: localhost:3306
  database: test

Webhook: # A formatação da webhook já é configurada, apenas coloque aqui as predefinições.
  ativar: false
  url: '' # Url da sua webhook

permissionUse: "punir.usar" # Permissao para utilizar os comandos

CheckPunishMenu:
  nothing_item:
    name: '&cEstá vázio por aqui...'
    lore:
      - ' '
      - ' &7Esperando por punições? &fTente voltar mais tarde.'
  punish_item:
    lore:
      - "&7Nome: &f@player"
      - ""
      - "&fInformações da punição:"
      - " &eMotivo: &7@reason"
      - " &eAutor: &7@author"
      - " &eProva: &7@prova"
      - " &eTempo: &7@time"
      - ""
      - "&7Clique com o botão esquerdo para copiar a prova."
      - "&cClique com o botão direito para revogar a punição."