MySQL:
  ativar: false
  usuario: root
  senha: ''
  host: localhost:3306
  database: test

permissionUse: "punir.usar" # Permissao para utilizar o comando /punir

CheckPunishMenu:
  name: '&ePunições de: @player'
  slots: 45
  next_page_slot: 45
  previous_page_slot: 37
  next_page_item:
    material: ARROW
    data: 0
    name: '&aPróxima página'
    lore:
      - ' '
      - ' &7Clique esquerdo/direito para ir para a próxima página.'
  previous_page_item:
    material: ARROW
    data: 0
    name: '&aPágina anterior'
    lore:
      - ' '
      - ' &7Clique esquerdo/direito para ir para a página anterior.'
  nothing_item:
    material: WEB
    data: 0
    name: '&cEstá vázio por aqui...'
    lore:
      - ' '
      - ' &7Esperando por punições? &fTente voltar mais tarde.'
    slot: 13
  punish_item:
    material: PAPER
    data: 0
    lore:
      - "&eNome: &7@player"
      - ""
      - "&eInformações da punição:"
      - " &eMotivo: @reason"
      - " &eTipo: @type"
      - " &eStatus: @status"
      - " &eProva: @prova"
      - ""
      - "&eClique com o botão esquerdo para copiar a prova."
      - "&cClique com o botão direito para revogar a punição."